### ISSUE TITLE
could not find package qiscus_chat_sdk

### ISSUE THREAD

**Issue by johnnypramadya** [qiscus/qiscus-chat-sdk-flutter-sample#3]
getting this error when Running "flutter pub get"

![Screen Shot 2020-12-22 at 10 24 21](https://user-images.githubusercontent.com/8390731/102845315-e1643000-443f-11eb-9591-52154fbe8bfc.png)

[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-ID)
    • Flutter version 1.22.5 at /Users/johnnypramadya/Downloads/flutter
    • Framework revision 7891006299 (11 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/johnnypramadya/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by adicatur** [comment]
Hi @johnnypramadya you can comment on these lines https://github.com/qiscus/qiscus-chat-sdk-flutter-sample/blob/master/pubspec.yaml#L27-L30, this one when you need to run chat SDK flutter locally. This error happens because could not find the chat SDK flutter in your local. After you comment on that line you will able to run the sample because it will use from pub dev https://github.com/qiscus/qiscus-chat-sdk-flutter-sample/blob/master/pubspec.yaml#L22

Anyway we will update the sample to avoid this confusion, thanks for the report

**Comment by johnnypramadya** [comment]
thanks

**Comment by apiep** [comment]
fixed on https://github.com/qiscus/qiscus-chat-sdk-flutter-sample/commit/fcc9dc4a220aa13586f02f010973b61a7f3de511
